Add code linting and github action
WordPress/twentytwentytwo pull request #73
Opened 2021-10-08 18:03 UTC by jffng

**Description**

This PR is a simpler alternative to #26. (Does not include the pre-commit hook)

**Testing Instructions** 

1. Run `npm install && composer install`
2. Try all of the test commands:
- `npm run lint:css`
- `composer run analyze functions.php`
- `composer run lint`
- `composer run standards:check`
- `composer run standards:fix`

2021-10-08 18:13 UTC, jffng commented on .github/workflows/lint.yml
> +    branches: [trunk,add/linting-github-actions]
Should remove this branch from the array before merging.

2021-10-08 20:19 UTC, jffng commented
Also @EvanHerman if you have a chance to review that would be great, thank you.

2021-10-08 20:29 UTC, gregrickaby commented on .github/workflows/stylelint.yml
> +        node-version: 12
@jffng I'm a big fan of Github Actions. Your workflows look really great! 

Question about the Node version though. The current LTS is 14 (which has support well into 2023) in contrast, Node 12 has an end-of-life date of 2022-04-30.

Thoughts about using Node 14 LTS instead?

Source: https://nodejs.org/en/about/releases/

2021-10-08 20:35 UTC, gregrickaby commented on .github/workflows/stylelint.yml
> +        PATTERN: "**/*.css"
@jffng Just passing along @ntwb [comment](https://github.com/WordPress/twentytwentytwo/pull/26#discussion_r724627705) that all files will need a blank new line. There are a few in this PR which are missing them.

Github flags them with a handy icon: 
![screenshot](https://dl.dropbox.com/s/gve230c2z1j0dul/Screen%20Shot%202021-10-08%20at%2015.34.47.png?dl=0)

2021-10-09 01:53 UTC, ntwb commented on .github/workflows/stylelint.yml
> +        node-version: 12
WordPress & Gutenberg's _official support is "LTS"

- https://github.com/WordPress/gutenberg/blob/trunk/.nvmrc#L1
- https://github.com/WordPress/wordpress-develop/blob/master/.nvmrc#L1

That said Gutenberg is still running Node.js v12 & v14 tests in GitHub Actions

Stylelint in the upcoming v14 release drops Node.js v10 support

With all that said, there's probably no need to use v12, switching to v14 should be fine

2021-10-09 02:18 UTC, ntwb requested changes
Looking good @jffng, a few more minor'ish suggestions

2021-10-09 02:18 UTC, ntwb commented on .editorconfig
> +end_of_line = crlf
```suggestion
# This file is for unifying the coding style for different editors and IDEs
# editorconfig.org

# WordPress Coding Standards
# https://make.wordpress.org/core/handbook/coding-standards/

root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = tab

[*.yml]
indent_style = space
indent_size = 2

[*.md]
trim_trailing_whitespace = false

```

There is no need to include the `[*.css]` section, CSS files inherit the `[*]` settings

The `[*.md]` section is required so that end-of-line and new-line support works as intented in md files such as the `README.md`, otherwise not everything will be on new lines as expected

Once this is merged and committed to the SVN WP repo, this file will not be required at all as it will inherit the root WP config from here https://github.com/WordPress/wordpress-develop/blob/master/.editorconfig

2021-10-09 02:18 UTC, ntwb commented on .github/workflows/lint.yml
> +        uses: actions/checkout@v2
I'd suggest _pinning_ these versions for all GitHub Actions, it ensures that only explicit versions are used, this is primarily I believe security related and is adhered to in the majority of P projects, e.g Gutenberg here for example:

https://github.com/WordPress/gutenberg/blob/trunk/.github/workflows/static-checks.yml#L25

These can be kept up-to-date with Dependabot:
> https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

2021-10-09 02:18 UTC, ntwb commented on .github/workflows/lint.yml
> +name: Continuous integration code quality checks
```suggestion
name: Code Quality - PHP
```

This makes it a little more readable when viewing the actions pipelines:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/1016458/136640073-f1ae2df3-9ebb-42c0-bcb3-3d7c0b7f90f6.png">

2021-10-09 02:18 UTC, ntwb commented on .github/workflows/stylelint.yml
> +name: Code Quality - Stylelint
```suggestion
name: Code Quality - CSS
```

Similar to the PHP change above, improve readability in the actions pipeline:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/1016458/136640092-cfdef892-3228-4563-a3d5-5e5ade53f9d6.png">

2021-10-09 02:18 UTC, ntwb commented on .github/workflows/lint.yml
> +        uses: actions/cache@v1
```suggestion
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
```

Updates v1 to the latest v2 release https://github.com/actions/cache/releases/tag/v2.1.6

2021-10-09 02:18 UTC, ntwb commented on .github/workflows/lint.yml
> +        uses: actions/cache@v1
```suggestion
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
```

Updates v1 to the latest v2 release https://github.com/actions/cache/releases/tag/v2.1.6

2021-10-09 02:18 UTC, ntwb commented on .github/workflows/stylelint.yml
> +      uses: actions/setup-node@v1
```suggestion
      uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # v2.4.1
```

Upgrades v1 to the latest setup-node v2.4.1 release https://github.com/actions/setup-node/releases/tag/v2.4.1

2021-10-09 02:18 UTC, ntwb commented on composer.json
> +{
This file has mixed indentation, currently using a mix of both tabs and spaces, it should use only tabs, this inherits the same settings from the `[*]` `.editorconfig` file pattern

The _dots_ in this indicates spaces, arrows indicate tabs:
<img width="239" alt="image" src="https://user-images.githubusercontent.com/1016458/136640424-ce967494-4fa1-4fb1-85a3-97528fa2ce46.png">

2021-10-09 02:18 UTC, ntwb commented on package.json
> +{
This file uses spaces for, it should use tabs, JSON files inherit the same settings from the [*] .editorconfig file pattern

2021-10-11 14:21 UTC, jffng commented
@ntwb @gregrickaby thank for the reviews and feedback! I think I addressed it all, including:

- Pinning gh action dependencies to specific commits / versions
- Using node 14 for the stylelint action
- Adding newlines to files that needed them
- Naming / formatting improvements

Going to merge this, thanks again.

2021-10-11 14:22 UTC, merged

2021-10-12 03:37 UTC, ntwb commented
@jffng Unsure if stylelint is actually working, it's not clear at all looking at the action run:

https://github.com/WordPress/twentytwentytwo/runs/3860275082?check_suite_focus=true

```shell
Run actions-hub/stylelint@master
  env:
    GITHUB_TOKEN: ***
    PATTERN: **/*.css
/usr/bin/docker run --name fa4e1462043903626f4732ae6d2265fbc0d97a_c97241 --label fa4e14 --workdir /github/workspace --rm -e GITHUB_TOKEN -e PATTERN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/twentytwentytwo/twentytwentytwo":"/github/workspace" fa4e14:62043903626f4732ae6d2265fbc0d97a
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning "stylelint" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
**/*.css
```

Also, the PHPCS run doesn't warn of the warnings:

https://github.com/WordPress/twentytwentytwo/runs/3860275079?check_suite_focus=true

```shell
Run composer standards:check -- --runtime-set ignore_warnings_on_exit true --runtime-set testVersion 5.8-
> @php ./vendor/squizlabs/php_codesniffer/bin/phpcs '--runtime-set' 'ignore_warnings_on_exit' 'true' '--runtime-set' 'testVersion' '5.8-'
W. 2 / 2 (100%)



FILE: index.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | WARNING | No PHP code was found in this file and short open tags
   |         | are not allowed by this install of PHP. This file may
   |         | be using short open tags but PHP does not allow
   |         | them. (Internal.NoCodeFound)
----------------------------------------------------------------------

Time: 159ms; Memory: 6MB
```